# Generated by Django 4.2.7 on 2025-04-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='admin',
            field=models.CharField(default='admin', max_length=150),
        ),
    ]
