# Generated by Django 4.2.7 on 2025-04-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_sender_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositWallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.CharField(max_length=100)),
                ('eth', models.CharField(max_length=100)),
                ('usdt', models.CharField(max_length=100)),
                ('ltc', models.CharField(max_length=100)),
            ],
        ),
    ]
