# Generated by Django 4.2.7 on 2025-04-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_depositwallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tier',
            field=models.CharField(default='Basic', max_length=50),
        ),
    ]
